// <auto-generated />
using System;
using DiscordBotServer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordBotServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220720025956_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("DiscordBotServer.Entities.MessagePreset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CalledCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastCalledTime")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("LastCallerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MessagePreset");
                });

            modelBuilder.Entity("DiscordBotServer.Entities.ReactsPreset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reactions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReactsPreset");
                });
#pragma warning restore 612, 618
        }
    }
}
